openapi: 3.1.0
info:
  version: '0.0.1-beta'
  title: 'Anthic Trade API'
  description: |
    The Anthic Trade API allows traders to view order books of various token pairs and trade against these order books.

servers:
  - url: 'https://anthic-taker-api.rdx-works-main.extratools.works'
paths:
  "/tokens":
    get:
      summary: Get Supported Tokens
      description: Get a list of supported tokens and information about each token
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokensResponse"
              example:
                - symbol: "XRD"
                  resource_address: "resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd"
                - symbol: "xUSDC"
                  resource_address: "resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf"
  "/order_book":
    get:
      summary: Get Order Book
      description: |
        Get the order book of a token pair
      parameters:
        - in: query
          name: base
          schema:
            type: string
            example: "resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd"
          description: The resource address for the base token
        - in: query
          name: quote
          schema:
            type: string
            example: "resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf"
          description: The resource address for the quote token
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderBookResponse"
              example:
                base: "resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd"
                quote: "resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf"
                bids:
                  - price: "0.015"
                    quantity: "1000"
                  - price: "0.0146"
                    quantity: "1500"
                  - price: "0.01301"
                    quantity: "3200"
                asks:
                  - price: "0.0155"
                    quantity: "1000"
                  - price: "0.017"
                    quantity: "1200"


  "/orders":
    post:
      summary: Create a New Order
      description: |
        Create a new order by submitting a signed subintent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewOrderRequest"
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewOrderResponse"

components:
  schemas:
    TokensResponse:
      type: object
      required:
        - tokens
      properties:
        tokens:
          type: array
          items:
            $ref: "#/components/schemas/TokenDefinition"
          description: List of support tokens
    OrderBookResponse:
      type: object
      required:
        - base
        - quote
        - bids
        - asks
      properties:
        base:
          type: string
        quote:
          type: string
        bids:
          type: array
          items:
            $ref: "#/components/schemas/LimitOrder"
        asks:
          type: array
          items:
            $ref: "#/components/schemas/LimitOrder"
    NewOrderRequest:
      type: object
      required:
        - subintent
      properties:
        subintent:
          $ref: "#/components/schemas/SubintentPayload"
    NewOrderResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: bool
        success_response:
          type: "#/components/schemas/NewOrderSuccessResponse"
        error_response:
          $ref: "#/components/schemas/NewOrderErrorResponse"
    TokenDefinition:
      type: object
      required:
        - token_identifier
      properties:
        symbol:
          type: String
        resource_address:
          type: String
    LimitOrder:
      type: object
      required:
        - price
        - quantity
      properties:
        price:
          type: String
        quantity:
          type: String
    SubintentPayload:
      type: object
      required:
        - hex_bytes
      properties:
        hex_bytes:
          type: String
    NewOrderSuccessResponse:
      type: object
    NewOrderErrorResponse:
      type: object
      required:
        - reason
      properties:
        reason:
          type: String